name: Audit

on:
  push:
  schedule:
    - cron: "40 10 * * *"

jobs:
  audit:
    uses: inrupt/javascript-style-configs/.github/workflows/reusable-audit.yml@v1.0.0
    secrets:
      WEBHOOK_E2E_FAILURE: ${{ secrets.WEBHOOK_E2E_FAILURE }}
